-- MySQL Script generated by MySQL Workbench
-- Sat Jun 17 16:36:43 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`customers` ;

CREATE TABLE IF NOT EXISTS `mydb`.`customers` (
  `id_costomers` INT NOT NULL AUTO_INCREMENT,
  `name_cm` VARCHAR(45) NULL,
  `address_cm` VARCHAR(45) NULL,
  `phone_cm` VARCHAR(45) NULL,
  `email_cm` VARCHAR(45) NULL,
  PRIMARY KEY (`id_costomers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`developers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`developers` ;

CREATE TABLE IF NOT EXISTS `mydb`.`developers` (
  `id_developers` INT NOT NULL AUTO_INCREMENT,
  `name_dv` VARCHAR(45) NULL,
  `sex_dv` VARCHAR(1) NULL,
  `address_dv` VARCHAR(45) NULL,
  `phone_dv` VARCHAR(15) NULL,
  `progects_idprogect` INT NULL,
  `dateOfBirtch` DATETIME NULL,
  `salary` INT NULL,
  `sur_name_dv` VARCHAR(45) NULL,
  PRIMARY KEY (`id_developers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`progects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`progects` ;

CREATE TABLE IF NOT EXISTS `mydb`.`progects` (
  `id_progects` INT NOT NULL AUTO_INCREMENT,
  `name_pr` VARCHAR(45) NULL,
  `time_pr` INT NULL,
  `cost_pr` INT NULL,
  `type_pr` VARCHAR(10) NULL,
  `customers_idcostomer` INT NULL,
  PRIMARY KEY (`id_progects`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`skills`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`skills` ;

CREATE TABLE IF NOT EXISTS `mydb`.`skills` (
  `id_skills` INT NOT NULL AUTO_INCREMENT,
  `skill` VARCHAR(45) NULL,
  PRIMARY KEY (`id_skills`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`companies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`companies` ;

CREATE TABLE IF NOT EXISTS `mydb`.`companies` (
  `id_companies` INT NOT NULL AUTO_INCREMENT,
  `name_cm` VARCHAR(45) NULL,
  `address_cm` VARCHAR(45) NULL,
  `phone_cm` VARCHAR(10) NULL,
  `email_cm` VARCHAR(45) NULL,
  PRIMARY KEY (`id_companies`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`developers_has_skills`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`developers_has_skills` ;

CREATE TABLE IF NOT EXISTS `mydb`.`developers_has_skills` (
  `developers_id_developers` INT NOT NULL,
  `skills_id_skills` INT NOT NULL,
  PRIMARY KEY (`developers_id_developers`, `skills_id_skills`),
  INDEX `fk_developers_has_skills_skills1_idx` (`skills_id_skills` ASC),
  INDEX `fk_developers_has_skills_developers_idx` (`developers_id_developers` ASC),
  CONSTRAINT `fk_developers_has_skills_developers`
    FOREIGN KEY (`developers_id_developers`)
    REFERENCES `mydb`.`developers` (`id_developers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_developers_has_skills_skills1`
    FOREIGN KEY (`skills_id_skills`)
    REFERENCES `mydb`.`skills` (`id_skills`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`developers_has_progects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`developers_has_progects` ;

CREATE TABLE IF NOT EXISTS `mydb`.`developers_has_progects` (
  `developers_id_developers` INT NOT NULL,
  `progects_id_progects` INT NOT NULL,
  PRIMARY KEY (`developers_id_developers`, `progects_id_progects`),
  INDEX `fk_developers_has_progects_progects1_idx` (`progects_id_progects` ASC),
  INDEX `fk_developers_has_progects_developers1_idx` (`developers_id_developers` ASC),
  CONSTRAINT `fk_developers_has_progects_developers1`
    FOREIGN KEY (`developers_id_developers`)
    REFERENCES `mydb`.`developers` (`id_developers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_developers_has_progects_progects1`
    FOREIGN KEY (`progects_id_progects`)
    REFERENCES `mydb`.`progects` (`id_progects`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`companies_has_developers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`companies_has_developers` ;

CREATE TABLE IF NOT EXISTS `mydb`.`companies_has_developers` (
  `companies_id_companies` INT NOT NULL,
  `developers_id_developers` INT NOT NULL,
  PRIMARY KEY (`companies_id_companies`, `developers_id_developers`),
  INDEX `fk_companies_has_developers_developers1_idx` (`developers_id_developers` ASC),
  INDEX `fk_companies_has_developers_companies1_idx` (`companies_id_companies` ASC),
  CONSTRAINT `fk_companies_has_developers_companies1`
    FOREIGN KEY (`companies_id_companies`)
    REFERENCES `mydb`.`companies` (`id_companies`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_companies_has_developers_developers1`
    FOREIGN KEY (`developers_id_developers`)
    REFERENCES `mydb`.`developers` (`id_developers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`companies_has_progects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`companies_has_progects` ;

CREATE TABLE IF NOT EXISTS `mydb`.`companies_has_progects` (
  `companies_id_companies` INT NOT NULL,
  `progects_id_progects` INT NOT NULL,
  PRIMARY KEY (`companies_id_companies`, `progects_id_progects`),
  INDEX `fk_companies_has_progects_progects1_idx` (`progects_id_progects` ASC),
  INDEX `fk_companies_has_progects_companies1_idx` (`companies_id_companies` ASC),
  CONSTRAINT `fk_companies_has_progects_companies1`
    FOREIGN KEY (`companies_id_companies`)
    REFERENCES `mydb`.`companies` (`id_companies`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_companies_has_progects_progects1`
    FOREIGN KEY (`progects_id_progects`)
    REFERENCES `mydb`.`progects` (`id_progects`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`customers_has_progects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`customers_has_progects` ;

CREATE TABLE IF NOT EXISTS `mydb`.`customers_has_progects` (
  `costomers_id_costomers` INT NOT NULL,
  `progects_id_progects` INT NOT NULL,
  PRIMARY KEY (`costomers_id_costomers`, `progects_id_progects`),
  INDEX `fk_costomers_has_progects_progects1_idx` (`progects_id_progects` ASC),
  INDEX `fk_costomers_has_progects_costomers1_idx` (`costomers_id_costomers` ASC),
  CONSTRAINT `fk_costomers_has_progects_costomers1`
    FOREIGN KEY (`costomers_id_costomers`)
    REFERENCES `mydb`.`customers` (`id_costomers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_costomers_has_progects_progects1`
    FOREIGN KEY (`progects_id_progects`)
    REFERENCES `mydb`.`progects` (`id_progects`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

